### ISSUE TITLE
controller.connect() hangs

### ISSUE THREAD

**Issue by xjtx21** [cncjs/cncjs-controller#1]
Hello, I am trying to integrate this module into an app and am having some difficulty getting it running. I'm new to socket.io and fairly new to node. I tried to run the code in the readme, just modified the first 2 lines and updated token and port. This is what I try and run (sorry for formatting):
************************************************************************************************************

```js
const io = require('socket.io-client'); //import io from 'socket.io-client';
const Controller = require('cncjs-controller'); //import Controller from 'cncjs-controller';

const controller = new Controller(io);
const host = 'http://127.168.0.12:8000'; // e.g. http://127.0.0.1:8000
const token = 'jt';
const options = {
    query: 'token=' + token
};

controller.connect(host, options, () => {
    const port = 'COM3';

    controller.openPort(port, {
        controllerType: 'Grbl', // Grbl|Smoothie|TinyG
        baudrate: 115200
    }, (err) => {
        if (err) {
            console.error(err);
            return;
        }

        controller.writeln('$$'); // View Grbl Settings
    });

    // Disconnect after 60 seconds
    setTimeout(() => {
        // Close port
        controller.closePort();

        // Close connection
        controller.disconnect();

        console.log('Timed Out');
    }, 60 * 1000);
});

controller.addListener('serialport:open', (options) => {
    const {
        port,
        baudrate,
        controllerType
    } = options;
    console.log('Connected to the port "${port}" with a baud rate of ${baudrate}.', { port, baudrate });
});

controller.addListener('serialport:close', (options) => {
    const { port } = options;
    console.log('The port "${port}" is disconnected.');
});

controller.addListener('serialport:write', (data, context) => {
    console.log('>', data);
});

controller.addListener('serialport:read', (data) => {
    console.log('<', data);
});
```

**************************************************************************************************************

I connect my arduino, then run the file with node from CLI and nothing happens. No error or anything, can't connect to host.

Any help is much appreciated!

**Comment by cheton** [comment]
i guess the host address you want to connect to is `http://192.168.0.12:8000/`, not `http://127.168.0.12:8000/`. Is it right?

**Comment by xjtx21** [comment]
Yes sorry it is http://192.168.0.12:8000/

**Comment by cheton** [comment]
The "cncjs-controler" package is purposed for communication between CNCjs app and CNCjs server, not for public use. 

If you want to integrate CNCjs with an external app, you may have to consider using cncjs-pendant-boilerplate instead:
https://github.com/cncjs/cncjs-pendant-boilerplate
https://github.com/cncjs/cncjs-pendant-boilerplate/blob/master/index.js
